-- Experiment17 MM2 modular v7 | module 01
Players = game:GetService("Players")
ReplicatedStorage = game:GetService("ReplicatedStorage")
RunService = game:GetService("RunService")
UIS = game:GetService("UserInputService")
Workspace = game:GetService("Workspace")
LP = Players.LocalPlayer
Mouse = LP:GetMouse()
Camera = Workspace.CurrentCamera
Library = loadstring(game:HttpGet(
"https://raw.githubusercontent.com/GasterNoCopyAble/Experiment17_GuiLib/main/Experiment17.lua"
))()
CombatTab = Library:CreateTab("Combat")
ESPTab = Library:CreateTab("ESP")
WorldTab = Library:CreateTab("World")
PlayerTab = Library:CreateTab("Player")
CameraTab = Library:CreateTab("Camera")
TargetTab = Library:CreateTab("Target")
RoundTab = Library:CreateTab("Round")
HUDTab = Library:CreateTab("HUD")
PerformanceTab = Library:CreateTab("Performance")
FlingTab = Library:CreateTab("Fling")
MiscTab = Library:CreateTab("Misc")
MurderSection = CombatTab:CreateSection("Murderer", true)
SheriffSection = CombatTab:CreateSection("Sheriff / Hero", true)
SilentSection = CombatTab:CreateSection("Silent Shot", false)
ESPMainSection = ESPTab:CreateSection("Player ESP", true)
ESPStyleSection = ESPTab:CreateSection("ESP Style", false)
ESPAdvancedSection = ESPTab:CreateSection("Advanced ESP", false)
ESPHistorySection = ESPTab:CreateSection("History / Trails", false)
ChamsSection = ESPTab:CreateSection("Player Chams", false)
GunSection = WorldTab:CreateSection("Dropped Gun", true)
CoinSection = WorldTab:CreateSection("Coins", false)
WarningSection = WorldTab:CreateSection("Murderer Warning", false)
RoleArrowSection = WorldTab:CreateSection("Role Arrow", false)
XRaySection = WorldTab:CreateSection("Smart XRay", false)
MovementSection = PlayerTab:CreateSection("Movement", true)
TeleportSection = PlayerTab:CreateSection("Teleport", false)
BookmarkSection = PlayerTab:CreateSection("Position Bookmarks", false)
GhostSection = PlayerTab:CreateSection("Invisible Ghost", false)
SpectateSection = CameraTab:CreateSection("Spectate", true)
FreecamSection = CameraTab:CreateSection("Freecam", false)
FreecamBookmarkSection = CameraTab:CreateSection("Freecam Bookmarks", false)
TargetSelectSection = TargetTab:CreateSection("Target Select", true)
TargetESPSection = TargetTab:CreateSection("Target Visuals", false)
TargetTeleportSection = TargetTab:CreateSection("Target Teleport", false)
PlayerListsSection = TargetTab:CreateSection("Pin / Ignore / Whitelist", false)
RoundMainSection = RoundTab:CreateSection("Round Events", true)
WeaponEventSection = RoundTab:CreateSection("Weapon Events", false)
HUDMainSection = HUDTab:CreateSection("HUD", true)
HUDEditSection = HUDTab:CreateSection("HUD Editor", false)
NotificationFilterSection = HUDTab:CreateSection("Notification Filters", false)
PerformanceMainSection = PerformanceTab:CreateSection("Update Rates", true)
PerformanceGuardSection = PerformanceTab:CreateSection("Adaptive Performance", false)
PerformanceProfileSection = PerformanceTab:CreateSection("Profiles", false)
TouchFlingSection = FlingTab:CreateSection("Touch Fling", true)
TargetFlingSection = FlingTab:CreateSection("Target Fling", true)
ProtectionSection = MiscTab:CreateSection("Protection", true)
KeybindSection = MiscTab:CreateSection("Keybinds", false)
FavoritesSection = MiscTab:CreateSection("Favorites", false)
State = {
Roles = {},
Murderer = nil,
Sheriff = nil,
Hero = nil,
RoleRemote = nil,
KillAll = false,
AutoShootMurderer = false,
ShootInProgress = false,
ShootBehindDistance = 3.5,
ShootFollowTime = 0.16,
ShootReturnDelay = 0.12,
LastKnifeAttack = 0,
LastGunShot = 0,
SilentShot = false,
SilentPart = "HumanoidRootPart",
ESP = false,
ESPHighlight = true,
ESPNames = true,
ESPUsername = false,
ESPRole = true,
ESPHealth = true,
ESPHealthBar = true,
ESPDistance = true,
ESPWeapon = true,
ESPBox = true,
ESPTracer = false,
ESPOffscreenArrows = true,
ESPMaxDistance = 2500,
ESPTextSize = 14,
ESPLineThickness = 1.4,
ESPHighlightTransparency = 0.66,
ESPColorMode = "Role Colors",
ESPCustomColor = Color3.fromRGB(170, 100, 255),
ESPInnocentColor = Color3.fromRGB(60, 225, 100),
ESPMurdererColor = Color3.fromRGB(235, 55, 55),
ESPSheriffColor = Color3.fromRGB(65, 125, 255),
ESPHeroColor = Color3.fromRGB(255, 225, 55),
ESPSkeleton = false,
ESPHeadDot = false,
ESPVisibleCheck = false,
ESPVisibleColor = Color3.fromRGB(80, 255, 180),
ESPDistanceFade = false,
ESPPreset = "Full",
ESPNameTextSize = 15,
ESPRoleTextSize = 13,
ESPInfoTextSize = 12,
ESPBackground = false,
ESPBackgroundTransparency = 0.45,
ESPRoundedBox = false,
ESPTargetHighlight = true,
ESPTargetColor = Color3.fromRGB(255, 120, 40),
ESPThreatPriority = false,
ESPThreatPriorityDistance = 55,
ESPVelocity = false,
ESPMovementDirection = false,
ESPJumpState = false,
ESPLastSeen = false,
ESPLastSeenDuration = 4,
ESPRoleTrail = false,
ESPPlayerTrailHistory = false,
ESPTrailSeconds = 3,
ESPUpdateRate = "30 Hz",
TargetPlayerName = "None",
TargetArrow = false,
TargetTracer = false,
TargetLockHUD = false,
TargetTeleportHeight = 8,
PinnedPlayers = {},
IgnoredPlayers = {},
WhitelistedPlayers = {},
WhitelistOnly = false,
PlayerCustomColors = {},
TargetCustomColor = Color3.fromRGB(255, 180, 55),
PlayerChams = false,
ChamsFillColor = Color3.fromRGB(145, 84, 255),
ChamsOutlineColor = Color3.fromRGB(255, 255, 255),
ChamsFillTransparency = 0.55,
ChamsOutlineTransparency = 0,
ChamsDepthMode = "AlwaysOnTop",
DroppedGunESP = false,
DroppedGunColor = Color3.fromRGB(80, 160, 255),
DroppedGunMaxDistance = 5000,
DroppedGunArrow = false,
DroppedGunDistanceHUD = false,
AutoGunPickup = false,
AutoGunPickupRange = 5000,
GunSpawnNotification = false,
LastKnownGun = nil,
GunPickupBusy = false,
LastAutoGunPickup = 0,
CoinESP = false,
CoinColor = Color3.fromRGB(255, 210, 45),
CoinMaxDistance = 1500,
CoinLimit = 120,
CoinNearestCount = 20,
NearestCoinArrow = false,
MurdererWarning = false,
MurdererWarningDistance = 35,
MurdererWarningCooldown = 2.5,
LastMurdererWarning = 0,
MurdererWarningArmed = true,
MurdererDistanceHUD = false,
MurdererApproachHUD = false,
MurdererDangerBar = false,
MurdererBehindWarning = false,
MurdererLOSWarning = false,
KnifeEquippedWarning = false,
GunEquippedWarning = false,
ClosingSpeedWarning = false,
ClosingSpeedThreshold = 18,
MurdererApproachSpeed = 0,
LastMurdererDistance = nil,
LastMurdererDistanceAt = 0,
LastClosingWarning = 0,
LastBehindWarning = 0,
LastLOSWarning = 0,
KnifeWasEquipped = false,
GunOwnersEquipped = {},
RoleChangeNotification = false,
PreviousRoles = {},
RoleCacheInitialized = false,
RoundStartNotification = false,
AutoResetVisualsRoundEnd = false,
RoundActive = false,
RoundIndex = 0,
RoleArrow = false,
RoleArrowTarget = "Murderer",
RoleArrowSize = 28,
RoleArrowRadius = 0.42,
XRay = false,
XRayTransparency = 0.72,
WalkSpeed = false,
WalkSpeedValue = 32,
JumpHack = false,
JumpPowerValue = 80,
Fly = false,
FlySpeed = 70,
FlyMode = "Camera",
MovementPreset = "Custom",
Noclip = false,
ClickTP = false,
ClickTPRequireAlt = false,
LastReturnCFrame = nil,
PositionBookmarks = {},
SelectedBookmark = "None",
BookmarkCounter = 0,
GhostMode = false,
GhostHeight = 15000,
GhostSpeed = 55,
Spectate = false,
SpectateTargetName = "None",
Freecam = false,
FreecamSpeed = 60,
FreecamBoost = 3,
FreecamSensitivity = 0.22,
FreecamFOV = 70,
FreecamWheelStep = 10,
FreecamFollowPlayer = false,
FreecamBookmark = nil,
WorldUpdateRate = "2 Hz",
AdaptivePerformance = false,
AdaptiveFPSMin = 45,
FPSGuard = false,
FPSGuardThreshold = 30,
FPSGuardActive = false,
LowFPSWarning = false,
LowFPSWarningThreshold = 35,
LastLowFPSWarning = 0,
ObjectCache = true,
CurrentFPS = 60,
FPSAccumulator = 0,
FPSFrames = 0,
FPSGuardLowSince = nil,
FPSGuardHighSince = nil,
MobilePerformanceProfile = false,
ScreenshotMode = false,
StreamerMode = false,
StreamerStyle = "Hide Usernames",
MinimalHUD = false,
HUDEditor = false,
HUDScale = 1,
HUDOpacity = 0.22,
NotificationFilters = {
Round = true,
Role = true,
Murderer = true,
Weapons = true,
Performance = true,
Target = true,
Gun = true,
System = true,
},
HeatmapESP = false,
HeatmapCellSize = 14,
HeatmapMaxCells = 70,
DeathMarkerESP = false,
BodyESP = false,
DeathTime = false,
ShootTPDelay = 0.04,
ShootRetry = false,
ShootRetryCount = 1,
ShootRetryDelay = 0.2,
ShootAttempts = 0,
AntiFling = false,
AntiFlingLinearThreshold = 260,
AntiFlingAngularThreshold = 120,
TouchFling = false,
TargetFlingActive = false,
FlingAllActive = false,
TargetFlingName = "None",
TargetFlingDuration = 0.85,
}
ENV = getgenv and getgenv() or _G
ENV.__E17_MM2_V7_STATE = State
Controls = {}
Connections = {}
DrawingObjects = {}
DrawingAvailable = type(Drawing) == "table" and type(Drawing.new) == "function"
function Connect(signal, callback)
local c = signal:Connect(callback)
Connections[#Connections + 1] = c
return c
end
function TrackDrawing(object)
if object then
DrawingObjects[#DrawingObjects + 1] = object
end
return object
end
function RemoveDrawing(object)
if object then
pcall(function() object:Remove() end)
end
end
